data_path: "data"
dataset_name: "flickr30k"
is_self_join: False
confidence_level: 0.95
proxy_score_cache: True
proxy_normalizing_style: "proportional"
bootstrap_trials: 1000
aggregator: "count"
proxy: "blip"