data_path: "data"
dataset_name: "quora_three"
is_self_join: False
confidence_level: 0.95
proxy_score_cache: True
proxy_normalizing_style: "proportional"
bootstrap_trials: 1000
aggregator: "avg"
proxy: "all-MiniLM-L6-v2"
log_level: "debug"